# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor
tensor1 = torch.rand(size=(7,7))

print(tensor1)


tensor([[0.2990, 0.2468, 0.6842, 0.6292, 0.5131, 0.6411, 0.5954],
        [0.9860, 0.9819, 0.4755, 0.5066, 0.8635, 0.8688, 0.1066],
        [0.4421, 0.6903, 0.7143, 0.8788, 0.9103, 0.6363, 0.7182],
        [0.5598, 0.5553, 0.3039, 0.4844, 0.6017, 0.8473, 0.6346],
        [0.1722, 0.3680, 0.6483, 0.9079, 0.5361, 0.4217, 0.4053],
        [0.3661, 0.2579, 0.2929, 0.0182, 0.2046, 0.8244, 0.8220],
        [0.4329, 0.4623, 0.6183, 0.2405, 0.0413, 0.5546, 0.0339]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2 = torch.rand(size=(1,7))

# Perform matrix multiplication
product = torch.matmul(tensor1,tensor2.T)

print(product)


tensor([[1.1957],
        [2.1120],
        [1.8101],
        [1.6931],
        [1.0580],
        [1.2799],
        [0.9731]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_tensor1 = torch.rand(size=(7,7))
rand_tensor2 = torch.rand(size=(1,7))

# Matrix multiply tensors
result = torch.matmul(rand_tensor1,rand_tensor2.T)

print(result)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
set = torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
set = torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device: ",device)

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)

print(tensor_A)
print(tensor_B)


Device:  cuda
tensor([[0.0237, 0.4910, 0.1235],
        [0.1143, 0.4725, 0.5751]], device='cuda:0')
tensor([[0.2952, 0.7967, 0.1957],
        [0.9537, 0.8426, 0.0784]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_A,tensor_B.T)

print(result,result.shape)

tensor([[0.4223, 0.4460],
        [0.5227, 0.5522]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
maximum = torch.max(result)
print(maximum)

# Find min
minimum = torch.min(result)
print(minimum)


tensor(0.5522, device='cuda:0')
tensor(0.4223, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
arg_max = torch.argmax(result)
print(arg_max)

# Find arg min
arg_min = torch.argmin(result)
print(arg_min)


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(random_tensor,random_tensor.shape)
print(squeezed_tensor,squeezed_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
